### ISSUE TITLE
Application for orbital wall reconstruction

### ISSUE THREAD

**Issue by lassoan** [sebastianandress/Slicer-SurfaceWrapSolidify_old#1]
@sebastianandress I'm not sure if you are a member on the Slicer forum, so I write to you here.

There is already a very promising use case of your effect: https://discourse.slicer.org/t/enhancing-orbital-walls-with-unsharp-mask-filtering/8440/4

Do you have any suggestions on how to set the parameters to get optimal results? It would be great if you could comment on the discussion.

**Comment by sebastianandress** [comment]
Thank you, I replied. This indeed looks like a nice application. The naming of the parameters definitely should be more clear, I try to work on that!

**Comment by lassoan** [comment]
Perfect, thanks a lot!
