### ISSUE TITLE
Excessive repository size

### ISSUE THREAD

**Issue by cpinter** [sebastianandress/Slicer-SurfaceWrapSolidify_old#7]
It takes a very long time to check out the repository, because although the size of the currently contained files is less than 40MB, the whole repo is 423MB. Maybe a large file was added then deleted? If it's not a problem would it be possible to remove it from the history so that it does not take this long to check out the source? Thank you!

**Comment by sebastianandress** [comment]
I finally tried to solve this issue using [bfg repo-cleaner](https://rtyley.github.io/bfg-repo-cleaner/). However it seems like some of the large files are also stored in the pull requests which GitHub stores as read-only in the refs/pull/ namespace. This blocks me from pushing the cleaned repository.

Have you ever encountered the same issue and maybe found a solution to this problem? In my opinion one brute-force method would be to delete the repository, recreate a fresh one and push the code (without history) again.

**Comment by sebastianandress** [comment]
I renamed this repository and created a new one at the same GitHub url without the old, large commit history.
